### ISSUE TITLE
Parcelamento de cartão

### ISSUE THREAD

**Issue by rodrigondec** [imobanco/zoop-wrapper#101]
# Resumo
Existe o `installment_plan` na zoop!
> https://docs.zoop.co/reference#post_v1-marketplaces-marketplace-id-transactions
> ![image](https://user-images.githubusercontent.com/3301060/92143356-902a2500-edeb-11ea-843c-44cb40b21ee4.png)

O zoop-wrapper precisa ter suporte à isso!

# Tarefas
- [x] alterar models/wrappers caso seja necessário para adicionar suporte à esse atributo
- [x] criar exemplos de transação de cartão parceladas (tanto presente quanto não presente)
- [x] criar testes se for necessário alterar

**Comment by PedroRegisPOAR** [comment]
## Alguns detalhes

- Note que `installment_plan` está vindo como `null` atualmente nos exemplos: [`"installment_plan": null,`](https://github.com/imobanco/zoop-wrapper/blob/c998ef645e7ac45578b039dcf044fde9a7cf0daa/examples/data/add_transaction_card_not_present.json#L88)

De acordo com [a zoop](https://docs.zoop.co/reference#post_v1-marketplaces-marketplace-id-transactions):
``` python
import requests

url = "https://api.zoop.ws/v1/marketplaces/marketplace_id/transactions"

payload = {"source": {
        "usage": "single_use",
        "installment_plan": {
            "mode": "interest_free",
            "number_installments": 5
        }
    }}
headers = {
    "accept": "application/json",
    "content-type": "application/json"
}

response = requests.request("POST", url, json=payload, headers=headers)
```

**Porquê o nesteamento é diferente?**

O `installment_plan` tem que virar uma field obrigatória no `get_required_fields` do `Card`? Atualmente ele já existe [aqui](https://github.com/imobanco/zoop-wrapper/blob/c998ef645e7ac45578b039dcf044fde9a7cf0daa/zoop_wrapper/models/transaction.py#L278). Se for considerado que esse não se torne algo bem complicado (como foi o caso do `Source`) como isso pode ser feito?

## Lembrar

- Explicar o que é o [installment_plan: ??](https://github.com/imobanco/zoop-wrapper/blob/c998ef645e7ac45578b039dcf044fde9a7cf0daa/zoop_wrapper/models/transaction.py#L92)
