### ISSUE TITLE
Documentar Card

### ISSUE THREAD

**Issue by rodrigondec** [imobanco/zoop-wrapper#33]
# Resumo
precisamos criar os `exemplos.py` do `CardWrapper`.

# Critério de aceite
Criar os exemplos de `add_card` e `retrieve_card`.

Adicionar na documentação (pasta `docs`) esse exemplo.

**Comment by PedroRegisPOAR** [comment]
Bloqueado conforme explicado em #72, a função `ZoopObject.from_dict` não está validando o argumento recebido, o que dificulta muito criar os exemplos.
