### ISSUE TITLE
Estorno Transação de crédito

### ISSUE THREAD

**Issue by rodrigondec** [imobanco/zoop-wrapper#77]
# Resumo
Precisamos ter o estorno de transação.

# Dados mágicos
existe uma mágica transação de id `720ba7a640564c229437f0644cdf37fe` que precisamos estornar.
> ela está em PROD

# Critérios de aceite
- [ ] fazer o estorno dessa transação mágica
- [ ] terminar o `cancel_transaction`
- [ ] fazer os testes desse método

**Comment by PedroRegisPOAR** [comment]
Link da documentação da Zoop referente a estorno:

https://docs.zoop.co/docs/estornando-transa%C3%A7%C3%B5es-cancelamento

Payload de exemplo:
```
{    
   "amount": 7, // Valor para estornar e devolver ao cartão
   "on_behalf_of": "1e4c8c9b9886419098c60c53f2e7a57e" // ID do Vendedor
}
```

**Comment by rodrigondec** [comment]
Na minha opnião, o método pode ficar algo desse tipo:

```python
    def cancel_transaction(self, identifier):
        """
        cancel a transaction

        Args:
            identifier: uuid id

        Returns:
            response
        """
        transaction_response = self.retrieve_transaction(identifier)
        transaction = transaction_response.instance

        data = {    
            "amount": transaction.amount, // Valor para estornar e devolver ao cartão
            "on_behalf_of": transaction.on_behalf_of // ID do Vendedor
        }

        url = self._construct_url(
            action="transactions", identifier=identifier, subaction="void"
        )
        return self._post(url, data=data)
```

O que acha?

**Comment by PedroRegisPOAR** [comment]
Acho genial. Eu não estava sabendo onde esse payload ia ser montado.

**Comment by rodrigondec** [comment]
Feito feito o estorno da transação mágica

![image](https://user-images.githubusercontent.com/3301060/84958233-4fb3e880-b0d3-11ea-8c71-2ec30f487819.png)
